#!/usr/bin/env python3
"""
d4_regge_bond_geometry.py
=========================

Regge curvature energy on the bonds of the D4 crystal, read in the static
register, where the compact axis x4 is Euclidean time.  The script supports
the monograph's subsection "The bond geometry of the static crystal".

What it checks
--------------
1. Point-group invariants.  W(F4), of order 1152, and its 576 proper
   rotations leave one symmetric tensor invariant (delta_ab) and two elastic
   tensors (the isotropic pair).  The hypercubic group leaves three elastic
   tensors, the third being cubic anisotropy.
   On the 24 gradients d_c phi_ab of a rotation two-form, W(F4) leaves three
   quadratic forms (the O(4) count), its proper rotations five (the SO(4)
   count) and the hypercubic group four.  For every one of them the
   coefficient of a compact-axis gradient of a spatial rotation equals that
   of a gradient along the rotation's own axis.  In the static register the
   first is J c^2, so the point group sets the microinertia at the
   longitudinal rotational stiffness.

2. Complexes.  The Delaunay cells of D4 are regular sixteen-cells centred on
   three cosets of deep holes.  A sixteen-cell has 24 edges but only 22 shape
   coordinates (its rigidity matrix has rank 22), so a generic change of its
   edge lengths admits no flat cell and curvature must be allowed inside it.
   Its two self-stresses are the bond-family differences: a tension constant
   on each of the three families {12|34}, {13|24}, {14|23} balances at every
   vertex when the three tensions sum to zero.  A cell therefore stays flat
   exactly when its three families stretch by the same total, as every
   metric does.
   Two simplicial divisions are built:
       'diag'     one diagonal per sixteen-cell, eight four-simplices each;
       'centred'  a cone from each cell centre, sixteen four-simplices each,
                  which keeps the full point group.
   Counts per unit cell, Euler characteristic and flatness are printed.

3. Hessian of the Regge action S = sum_f A_f delta_f at the flat lattice.
   Schlafli's identity gives H = (dA/dl)^T (d delta/dl).  Dihedral angles come
   from squared edge lengths through the Gram matrix of barycentric
   gradients, with derivatives by complex step.  The script checks symmetry,
   the slide zero modes, and the Bloch transform against a real-space sum.

4. Long-wavelength form.  A metric perturbation h changes edge e, of length
   l_e and direction n_e, by (1/2) l_e n_e.h.n_e.  After exact zero modes are
   projected out and the edge combinations that change no metric component
   are integrated out, the energy per cell is compared with
   (V_cell/2) [sqrt(g) R]^(2) for seven directions, compact axis included.

5. A defect line at rest couples to h_44 alone.  At zero compact wavevector
   the stationary metric has h_44 = 2 Phi and transverse h_ij = -2 Psi P_ij,
   and gamma = Psi/Phi.

6. The two bond-family differences, which change no metric component: their
   energy at k = 0, with every other edge relaxed, in each division.

7. Longitudinal waves of the static register, wave along x with fields u_x
   and u_4: u_4 free; u_4 the condensate phase with chemical potential
   m0 c^2 (reading A) or m0 v_p^2 (reading B).

Conventions
-----------
Coordinates are in units where D4 nearest neighbours are sqrt(2) apart, so
the unit-cell volume is V_cell = 2.  The second-order part of sqrt(g) R is
    -1/4 dh.dh + 1/2 (d.h)^2 - 1/2 (d.h).d(tr h) + 1/4 (d tr h)^2,
whose sign is fixed by the conformal mode h = 2 sigma delta, which gives
+6 (d sigma)^2, and int sqrt(g) R = 2 sum_f A_f delta_f.

Usage:    python3 d4_regge_bond_geometry.py
Requires: numpy, scipy
Runtime:  under a minute.

Repository: https://github.com/uberflyx/CosseratSupersolidLattice
Authors:    Mitchell Cox, Warren Carlson (University of the Witwatersrand)
"""
import itertools

import numpy as np
import scipy.sparse as sparse

BOX = 6          # periodic box side in coordinate units (even)
V_CELL = 2.0     # volume of one D4 unit cell in these units


# =========================================================================
# 1. Point-group invariants
# =========================================================================

def f4_roots():
    """The 48 roots of F4: +-e_i, +-e_i +- e_j and (+-1/2, +-1/2, +-1/2, +-1/2)."""
    roots = []
    for i in range(4):
        for s in (1, -1):
            v = np.zeros(4); v[i] = s; roots.append(v)
    for i, j in itertools.combinations(range(4), 2):
        for s, t in itertools.product((1, -1), repeat=2):
            v = np.zeros(4); v[i] = s; v[j] = t; roots.append(v)
    for s in itertools.product((0.5, -0.5), repeat=4):
        roots.append(np.array(s))
    return roots


def reflection_group(roots):
    """Close the group generated by the reflections in the given roots."""
    gens = [np.eye(4) - 2 * np.outer(r, r) / (r @ r) for r in roots]
    key = lambda M: tuple(np.round(2 * M).astype(int).ravel())
    group = {key(np.eye(4)): np.eye(4)}
    frontier = [np.eye(4)]
    while frontier:
        new = []
        for M in frontier:
            for R in gens:
                N = R @ M
                k = key(N)
                if k not in group:
                    group[k] = N
                    new.append(N)
        frontier = new
    return list(group.values())


def sym2_rep(M, basis):
    """Action of M on symmetric 4x4 tensors, in an orthonormal basis."""
    return np.array([[np.sum(Bi * (M @ Bj @ M.T)) for Bj in basis] for Bi in basis])


def elastic_rep(R):
    """Action on Sym^2 of the 10-dimensional space: elastic tensors, 55 components."""
    idx = [(i, j) for i in range(10) for j in range(i, 10)]
    out = np.zeros((55, 55))
    for p, (i, j) in enumerate(idx):
        ni = np.sqrt(2) if i != j else 1.0
        for q, (k, l) in enumerate(idx):
            val = R[k, i] * R[l, j] + R[l, i] * R[k, j]
            if k == l:
                val /= 2
            nk = np.sqrt(2) if k != l else 1.0
            out[q, p] = val * ni / nk
    return out


def invariant_counts(group):
    """Dimensions of the invariant subspaces (trace of the group-averaged projector)."""
    basis = []
    for a in range(4):
        for b in range(a, 4):
            E = np.zeros((4, 4)); E[a, b] = E[b, a] = 1.0
            basis.append(E / np.linalg.norm(E))
    P2 = sum(sym2_rep(M, basis) for M in group) / len(group)
    P4 = sum(elastic_rep(sym2_rep(M, basis)) for M in group) / len(group)
    return int(round(np.trace(P2))), int(round(np.trace(P4)))


# =========================================================================
# 2. The two simplicial divisions of the D4 Delaunay tessellation
# =========================================================================

PAIRS = list(itertools.combinations(range(5), 2))
TRIPLES = list(itertools.combinations(range(5), 3))


def build_complex(n=BOX, kind="centred", diag_axis=(3, 0, 0)):
    """Periodic D4 box of side n.  Positions are held in half-units X = 2x so
    that the hole positions are integers.  Vertex type 0 is a lattice node;
    types 1-3 are the centres of the three cosets of sixteen-cells."""
    n2 = 2 * n
    nodes = [X for X in itertools.product(range(0, n2, 2), repeat=4)
             if (sum(X) // 2) % 2 == 0]
    coset = [(0, 0, 0, 0), (2, 0, 0, 0), (1, 1, 1, 1), (1, 1, 1, -1)]
    axes = {1: [(2, 0, 0, 0), (0, 2, 0, 0), (0, 0, 2, 0), (0, 0, 0, 2)],
            2: [(1, 1, 1, 1), (1, 1, -1, -1), (1, -1, 1, -1), (1, -1, -1, 1)],
            3: [(1, 1, 1, -1), (1, 1, -1, 1), (1, -1, 1, 1), (-1, 1, 1, 1)]}
    wrap = lambda X: tuple(c % n2 for c in X)
    vid, vtype, vpos = {}, [], []

    def vertex(t, X):
        key = (t, wrap(X))
        if key not in vid:
            vid[key] = len(vtype)
            vtype.append(t)
            vpos.append(np.array(key[1], float) / 2)
        return vid[key]

    for P in nodes:
        vertex(0, P)
    simplices = []
    for P in nodes:
        for t in (1, 2, 3):
            q = np.add(P, coset[t])
            D = [np.array(d) for d in axes[t]]
            if kind == "diag":
                jd = diag_axis[t - 1]
                others = [j for j in range(4) if j != jd]
                for s in itertools.product((1, -1), repeat=3):
                    pts = [q + D[jd], q - D[jd]] + [q + s[a] * D[j] for a, j in enumerate(others)]
                    simplices.append(([vertex(0, p) for p in pts], np.array(pts, float) / 2))
            else:
                qc = vertex(t, q)
                for s in itertools.product((1, -1), repeat=4):
                    pts = [q] + [q + s[j] * D[j] for j in range(4)]
                    ids = [qc] + [vertex(0, p) for p in pts[1:]]
                    simplices.append((ids, np.array(pts, float) / 2))
    eid, edges, tid, tris = {}, [], {}, []
    s_edges = np.zeros((len(simplices), 10), int)
    s_tris = np.zeros((len(simplices), 10), int)
    for si, (ids, pts) in enumerate(simplices):
        for pi, (a, b) in enumerate(PAIRS):
            key = frozenset((ids[a], ids[b]))
            if key not in eid:
                eid[key] = len(edges)
                edges.append((ids[a], ids[b], pts[b] - pts[a]))
            s_edges[si, pi] = eid[key]
        for ti, tri in enumerate(TRIPLES):
            key = frozenset(ids[v] for v in tri)
            if key not in tid:
                tid[key] = len(tris)
                tris.append(tuple(sorted(key)))
            s_tris[si, ti] = tid[key]
    tets = {frozenset(q) for ids, _ in simplices for q in itertools.combinations(ids, 4)}
    return dict(n=n, kind=kind, vtype=np.array(vtype), vpos=np.array(vpos),
                simplices=simplices, edges=edges, tris=tris, eid=eid,
                s_edges=s_edges, s_tris=s_tris, n_tets=len(tets), n_cells=len(nodes))


def sixteen_cell_rigidity():
    """Rank of the rigidity matrix of a regular sixteen-cell (8 vertices +-e_i)."""
    V = [s * np.eye(4)[i] for i in range(4) for s in (1, -1)]
    E = [(a, b) for a, b in itertools.combinations(range(8), 2) if not np.allclose(V[a], -V[b])]
    R = np.zeros((len(E), 32))
    for r, (a, b) in enumerate(E):
        d = V[a] - V[b]
        R[r, 4 * a:4 * a + 4] = d
        R[r, 4 * b:4 * b + 4] = -d
    return len(E), np.linalg.matrix_rank(R)


def sixteen_cell_self_stresses():
    """Show that the two self-stresses of a regular sixteen-cell are the family differences.

    A self-stress is a tension omega_e on the edges with sum_e omega_e (x_a - x_b) = 0 at
    every vertex, i.e. a vector in the left null space of the rigidity matrix.  An edge-length
    change is produced by moving the vertices (to first order) exactly when it is orthogonal to
    every self-stress.  Returns the equilibrium residual of the family-difference patterns, their
    distance from the left null space, and the family totals of a random metric-induced change.
    """
    V = [s * np.eye(4)[i] for i in range(4) for s in (1, -1)]
    E = [(a, b) for a, b in itertools.combinations(range(8), 2) if not np.allclose(V[a], -V[b])]
    R = np.zeros((len(E), 32))
    for r, (a, b) in enumerate(E):
        d = V[a] - V[b]
        R[r, 4 * a:4 * a + 4] = d
        R[r, 4 * b:4 * b + 4] = -d
    U, s, _ = np.linalg.svd(R)
    rank = int(np.sum(s > 1e-10))
    stresses = U[:, rank:]
    # Family of an edge: the pair of coordinate planes {12|34}, {13|24}, {14|23} its axis joins.
    family_of_plane = {(0, 1): 0, (2, 3): 0, (0, 2): 1, (1, 3): 1, (0, 3): 2, (1, 2): 2}
    fam = np.array([family_of_plane[tuple(sorted((int(np.argmax(np.abs(V[a]))),
                                                   int(np.argmax(np.abs(V[b]))))))] for a, b in E])
    D = np.stack([(fam == 0) * 1.0 - (fam == 1), (fam == 1) * 1.0 - (fam == 2)], axis=1)
    equilibrium = float(np.abs(R.T @ D).max())
    in_null = float(np.linalg.norm(stresses @ (stresses.T @ D) - D))
    rng = np.random.default_rng(7)
    h = rng.normal(size=(4, 4)); h = h + h.T
    dl = np.array([(V[a] - V[b]) @ h @ (V[a] - V[b]) for a, b in E])
    totals = [float(dl[fam == k].sum()) for k in range(3)]
    return stresses.shape[1], equilibrium, in_null, totals


def curvature_invariants(generators):
    """Invariant quadratic forms on the gradients d_c phi_ab of a rotation two-form.

    The 24 components T_(ab),c = d_c phi_ab carry the representation Lambda^2 (x) R^4.  The
    invariant symmetric forms Q (with R^T Q R = Q for every generator R) are found as a null
    space.  For each form the script compares three coefficients for the spatial rotation
    phi_12 (a rotation about the third spatial axis): a gradient along the compact axis, along
    the rotation axis (longitudinal), and across it (transverse).  In the static register the
    first is J c^2, the microinertia read through x4 = ct.
    """
    pairs = list(itertools.combinations(range(4), 2))

    def rep(M):
        L = np.zeros((6, 6))
        for j, (a, b) in enumerate(pairs):
            Eab = np.zeros((4, 4)); Eab[a, b] = 1.0; Eab[b, a] = -1.0
            F = M @ Eab @ M.T
            for i, (c, d) in enumerate(pairs):
                L[i, j] = F[c, d]
        return np.kron(L, M)

    n = 24
    idx = [(i, j) for i in range(n) for j in range(i, n)]
    blocks = []
    for g in generators:
        Rg = rep(g)
        B = np.zeros((n * n, len(idx)))
        for t, (i, j) in enumerate(idx):
            Q = np.zeros((n, n)); Q[i, j] = Q[j, i] = 1.0
            B[:, t] = (Rg.T @ Q @ Rg - Q).ravel()
        blocks.append(B)
    _, s, Wt = np.linalg.svd(np.vstack(blocks), full_matrices=False)
    null = Wt[int(np.sum(s > 1e-9)):]

    def grad(k, pair):
        phi = np.zeros(6); phi[pairs.index(pair)] = 1.0
        return np.kron(phi, np.eye(4)[k])

    rows = []
    for c in null:
        Q = np.zeros((n, n))
        for t, (i, j) in enumerate(idx):
            Q[i, j] = Q[j, i] = c[t]
        compact, longitudinal, transverse = (grad(k, (0, 1)) @ Q @ grad(k, (0, 1)) for k in (3, 2, 0))
        rows.append((compact, longitudinal, transverse))
    return np.array(rows)


# =========================================================================
# 3. Regge Hessian and Bloch transform
# =========================================================================

def dihedral_angles(L2):
    """Interior dihedral angles of four-simplices at their ten triangles,
    from the ten squared edge lengths L2[..., PAIRS order]."""
    idx = {p: k for k, p in enumerate(PAIRS)}
    l2 = lambda a, b: L2[..., idx[(min(a, b), max(a, b))]]
    G = np.empty(L2.shape[:-1] + (4, 4), L2.dtype)
    for i in range(1, 5):
        for j in range(1, 5):
            lij = 0 * L2[..., 0] if i == j else l2(i, j)
            G[..., i - 1, j - 1] = 0.5 * (l2(0, i) + l2(0, j) - lij)
    C = np.vstack([-np.ones(4), np.eye(4)])          # barycentric gradients
    M = np.einsum('ai,...ij,bj->...ab', C, np.linalg.inv(G), C)
    out = np.empty(L2.shape[:-1] + (10,), L2.dtype)
    for ti, tri in enumerate(TRIPLES):
        d, e = [v for v in range(5) if v not in tri]
        out[..., ti] = np.arccos(-M[..., d, e] / np.sqrt(M[..., d, d] * M[..., e, e]))
    return out


def regge_hessian(cx):
    """Sparse Hessian of S = sum_f A_f delta_f at the flat configuration."""
    S = len(cx['simplices'])
    L = np.array([[np.linalg.norm(p[b] - p[a]) for a, b in PAIRS] for _, p in cx['simplices']])
    theta = dihedral_angles(L ** 2).real
    step = 1e-30
    dtheta = np.empty((S, 10, 10))
    for e in range(10):
        Lc = L.astype(complex)
        Lc[:, e] += 1j * step
        dtheta[:, :, e] = dihedral_angles(Lc ** 2).imag / step
    T = len(cx['tris'])
    angle_sum = np.zeros(T)
    np.add.at(angle_sum, cx['s_tris'].ravel(), theta.ravel())
    deficit = 2 * np.pi - angle_sum
    elen = np.array([np.linalg.norm(d) for _, _, d in cx['edges']])
    eid = cx['eid']
    tri_edges = np.array([[eid[frozenset((a, b))], eid[frozenset((b, c))], eid[frozenset((a, c))]]
                          for a, b, c in cx['tris']])
    la, lb, lc = (elen[tri_edges[:, k]] for k in range(3))
    area = 0.25 * np.sqrt(2 * la**2 * lb**2 + 2 * lb**2 * lc**2 + 2 * lc**2 * la**2
                          - la**4 - lb**4 - lc**4)
    darea = np.stack([la * (lb**2 + lc**2 - la**2), lb * (la**2 + lc**2 - lb**2),
                      lc * (la**2 + lb**2 - lc**2)], 1) / (8 * area[:, None])
    rows, cols, vals = [], [], []
    for ti in range(10):
        f = cx['s_tris'][:, ti]
        for k in range(3):
            for el in range(10):
                rows.append(tri_edges[f, k])
                cols.append(cx['s_edges'][:, el])
                vals.append(-darea[f, k] * dtheta[:, ti, el])
    E = len(cx['edges'])
    H = sparse.coo_matrix((np.concatenate(vals), (np.concatenate(rows), np.concatenate(cols))),
                          shape=(E, E)).tocsr()
    return H, deficit


def translation_classes(cx):
    """Group edges into translation classes (endpoint types and displacement)."""
    vt = cx['vtype']
    keys, cls = {}, []
    for i, j, d in cx['edges']:
        k1 = (vt[i], vt[j], tuple(np.round(2 * d).astype(int)))
        k2 = (vt[j], vt[i], tuple(np.round(-2 * d).astype(int)))
        key = min(k1, k2)
        keys.setdefault(key, len(keys))
        cls.append(keys[key])
    disp = np.zeros((len(keys), 4))
    types = [None] * len(keys)
    for (ti, tj, d2), c in keys.items():
        disp[c] = np.array(d2, float) / 2
        types[c] = (ti, tj)
    return np.array(cls), disp, types


def bloch_operator(cx, H):
    """Return k -> H(k) on the translation classes, and the class geometry."""
    cls, disp, types = translation_classes(cx)
    n, vpos = cx['n'], cx['vpos']
    mid = np.array([vpos[i] + d / 2 for i, _, d in cx['edges']])
    ref = {}
    for e, c in enumerate(cls):
        ref.setdefault(c, e)
    nc = len(disp)

    def Hk(k):
        out = np.zeros((nc, nc), complex)
        for a in range(nc):
            row = H.getrow(ref[a])
            dx = mid[row.indices] - mid[ref[a]]
            dx = (dx + n / 2) % n - n / 2
            np.add.at(out[a], cls[row.indices], row.data * np.exp(1j * dx @ k))
        return out
    return Hk, cls, disp, types, mid


# =========================================================================
# 4. Long-wavelength comparison with Einstein-Hilbert
# =========================================================================

def metric_basis():
    basis = []
    for a in range(4):
        for b in range(a, 4):
            E = np.zeros((4, 4)); E[a, b] = E[b, a] = 1.0
            basis.append(E)
    return basis


def eh_second_order(h, k):
    """Space average of the second-order part of sqrt(g) R for g = delta + h cos(k.x)."""
    kh, tr = k @ h, np.trace(h)
    return 0.5 * (-0.25 * (k @ k) * np.sum(h * h) + 0.5 * kh @ kh
                  - 0.5 * (k @ h @ k) * tr + 0.25 * (k @ k) * tr ** 2)


def eh_form(k, basis):
    """Continuum energy per cell, (V_cell/2) [sqrt(g) R]^(2), as a 10x10 form."""
    out = np.zeros((10, 10))
    for i, bi in enumerate(basis):
        for j, bj in enumerate(basis):
            out[i, j] = 0.5 * V_CELL * 0.5 * (eh_second_order(bi + bj, k)
                                              - eh_second_order(bi, k) - eh_second_order(bj, k))
    return out


def effective_metric_form(Hk, M, k, tol=1e-9):
    """Energy per cell as a 10x10 form on metric components, after projecting
    out exact zero modes and integrating out the non-metric complement."""
    Hm = Hk(k)
    w, U = np.linalg.eigh(Hm)
    Z = U[:, np.abs(w) < tol * np.abs(w).max()]
    Mp = M - Z @ (Z.conj().T @ M)
    B = np.hstack([Z, Mp])
    Q, _ = np.linalg.qr(B, mode='complete')
    N = Q[:, np.linalg.matrix_rank(B, tol=1e-10):]
    HMM = Mp.conj().T @ Hm @ Mp
    if N.shape[1]:
        HMN = Mp.conj().T @ Hm @ N
        HMM = HMM - HMN @ np.linalg.solve(N.conj().T @ Hm @ N, HMN.conj().T)
    return 0.25 * np.real(HMM), Z.shape[1]


# =========================================================================
# 7. Longitudinal sector of the static register
# =========================================================================

def longitudinal_speeds(lam, mu, A, B):
    """Phase speeds w/(ck) of the (u_x, u_4) block for a wave along x, with
    four-dimensional Lame constants lam, mu and extra u_4 stiffnesses A
    (spatial gradients) and B (compact-axis gradients).  Q = k4^2 at k = 1;
    a real speed s is a root Q = -s^2 of det M(Q) = 0."""
    a2 = mu * (lam + 2 * mu + B)
    a1 = (lam + 2 * mu) * (lam + 2 * mu + B) + mu * (mu + A) - (lam + mu) ** 2
    a0 = (lam + 2 * mu) * (mu + A)
    return np.roots([a2, a1, a0])


# =========================================================================
# main
# =========================================================================

def main():
    print("1. Point-group invariants (symmetric tensors, elastic tensors)")
    G = reflection_group(f4_roots())
    Gp = [M for M in G if np.linalg.det(M) > 0]
    Gb4 = [M for M in G if np.allclose(np.abs(M), np.round(np.abs(M)))
           and np.allclose(np.abs(M).sum(1), 1)]
    for name, grp in (("W(F4)", G), ("W(F4) proper rotations", Gp), ("hypercubic W(B4)", Gb4)):
        print(f"   {name:24s} order {len(grp):5d}:  {invariant_counts(grp)}")

    print("   rotation-gradient invariants: count; max |compact - longitudinal|; transverse differs?")
    refl = [np.eye(4) - 2 * np.outer(r, r) / (r @ r) for r in f4_roots()]
    b4 = [np.eye(4) - 2 * np.outer(r, r) / (r @ r)
          for r in [np.eye(4)[i] for i in range(4)]
          + [np.eye(4)[i] - np.eye(4)[j] for i in range(4) for j in range(i + 1, 4)]]
    for name, gens in (("W(F4)", refl), ("W(F4) proper rotations", [refl[0] @ g for g in refl]),
                       ("hypercubic W(B4)", b4)):
        rows = curvature_invariants(gens)
        print(f"   {name:24s} {len(rows)} forms;  {np.abs(rows[:, 0] - rows[:, 1]).max():.1e};  "
              f"{bool(np.abs(rows[:, 0] - rows[:, 2]).max() > 1e-6)}")

    ne, rank = sixteen_cell_rigidity()
    print(f"\n   sixteen-cell: {ne} edges, rigidity rank {rank} = 4*8 - 10 shape coordinates "
          f"({ne - rank} self-stresses)")
    n_s, eq_res, null_res, totals = sixteen_cell_self_stresses()
    print(f"   family differences: equilibrium residual {eq_res:.1e}, distance from the "
          f"{n_s}-dimensional self-stress space {null_res:.1e}")
    print(f"   a random metric stretches the three families by totals {np.round(totals, 10)}")

    basis = metric_basis()
    k_dirs = {"e4 (compact axis)": [0, 0, 0, 1], "e1": [1, 0, 0, 0], "(1,1,0,0)": [1, 1, 0, 0],
              "(1,0,0,1)": [1, 0, 0, 1], "(1,1,1,1)": [1, 1, 1, 1], "(1,2,3,4)": [1, 2, 3, 4],
              "(0.3,-1.7,0.9,0.4)": [0.3, -1.7, 0.9, 0.4]}
    for kind in ("diag", "centred"):
        cx = build_complex(BOX, kind)
        nc = cx['n_cells']
        V, E, F, T, S = len(cx['vtype']), len(cx['edges']), len(cx['tris']), cx['n_tets'], len(cx['simplices'])
        print(f"\n2. [{kind}] per unit cell V,E,F,T,S = "
              f"{V/nc:g}, {E/nc:g}, {F/nc:g}, {T/nc:g}, {S/nc:g};  Euler characteristic {V-E+F-T+S}")
        H, deficit = regge_hessian(cx)
        print(f"   flat: max |deficit| = {np.abs(deficit).max():.1e};  "
              f"Hessian asymmetry {abs(H - H.T).max():.1e}")
        Hk, cls, disp, types, mid = bloch_operator(cx, H)
        M = np.array([[0.5 * d @ b @ d / np.linalg.norm(d) for b in basis] for d in disp]).astype(complex)

        # 3. Bloch normalisation and slides
        kc = 2 * np.pi * np.array([1, 0, 0, 1]) / BOX
        h = np.zeros((4, 4)); h[1, 2] = h[2, 1] = 1.0; h[0, 0] = 0.3
        a = np.array([0.5 * d @ h @ d / np.linalg.norm(d) for d in disp], complex)
        dl = np.real(a[cls] * np.exp(1j * mid @ kc))
        e_real = 0.5 * dl @ (H @ dl) / nc
        e_bloch = 0.25 * np.real(a.conj() @ Hk(kc) @ a)
        print(f"3. Bloch check: real-space {e_real:.12f}, Bloch {e_bloch:.12f}")
        kg = np.array([0.013, -0.021, 0.034, 0.017])
        w = np.linalg.eigvalsh(Hk(kg))
        n_zero = int(np.sum(np.abs(w) < 1e-9 * np.abs(w).max()))
        print(f"   exact zero modes at a generic small k: {n_zero}")

        # 4. Einstein-Hilbert comparison
        print("4. energy per cell / (V_cell/2)[sqrt(g)R]^(2) at |k| = 1e-3, after elimination")
        for name, d in k_dirs.items():
            k = 1e-3 * np.array(d, float) / np.linalg.norm(d)
            Eff, _ = effective_metric_form(Hk, M, k)
            Geh = eh_form(k, basis)
            s = np.sum(Eff * Geh) / np.sum(Geh * Geh)
            res = np.linalg.norm(Eff - s * Geh) / np.linalg.norm(Geh)
            print(f"   {name:20s} ratio {s:.6f}  residual {res:.1e}")

        # 5. Defect line at rest: source on h_44 at k4 = 0
        if kind == "centred":
            print("5. defect line along the compact axis (source on h_44, k4 = 0)")
            i44 = [i for i, b in enumerate(basis) if b[3, 3] == 1][0]
            for d in ([1, 0, 0], [1, 1, 0], [1, 1, 1], [0.3, -1.7, 0.9]):
                k = np.array(d + [0.0]); k = 2e-3 * k / np.linalg.norm(k)
                Eff, _ = effective_metric_form(Hk, M, k)
                J = np.zeros(10); J[i44] = 1.0
                hv = np.linalg.pinv(2 * Eff, rcond=1e-10) @ J
                Hmat = sum(c * b for c, b in zip(hv, basis))
                ks = k[:3] / np.linalg.norm(k[:3])
                P = np.eye(3) - np.outer(ks, ks)
                psi = np.trace(P @ Hmat[:3, :3] @ P) / 4     # transverse h_ij = 2 psi P_ij
                phi = Hmat[3, 3] / 2                         # h_44 = 2 phi
                print(f"   k along {d}: Phi = {phi:+.4e}, Psi = {-psi:+.4e}, gamma = {-psi/phi:.6f}")

        # 6. Bond-family differences
        d4 = [c for c in range(len(disp)) if types[c] == (0, 0) and np.isclose(np.linalg.norm(disp[c]), np.sqrt(2))]
        aux = [c for c in range(len(disp)) if c not in d4]
        fam = {}
        for c in d4:
            plane = tuple(sorted(np.nonzero(np.round(disp[c]))[0]))
            f = {(0, 1): 0, (2, 3): 0, (0, 2): 1, (1, 3): 1, (0, 3): 2, (1, 2): 2}[plane]
            fam.setdefault(f, []).append(d4.index(c))
        for kmag in (0.0, 1e-2):
            k = kmag * np.array([0.3, -1.7, 0.9, 0.4]) / np.linalg.norm([0.3, -1.7, 0.9, 0.4])
            Hm = Hk(k)
            Heff = (Hm[np.ix_(d4, d4)] - Hm[np.ix_(d4, aux)]
                    @ np.linalg.pinv(Hm[np.ix_(aux, aux)], rcond=1e-10) @ Hm[np.ix_(aux, d4)])
            Heff = 0.5 * (Heff + Heff.conj().T)
            pats = []
            for f1, f2 in ((0, 1), (1, 2)):
                v = np.zeros(len(d4)); v[fam[f1]] = 1.0; v[fam[f2]] = -1.0
                pats.append(v / np.linalg.norm(v))
            P = np.linalg.qr(np.array(pats).T)[0].T          # orthonormal basis of the pair
            Hff = P @ Heff @ P.T
            w12 = np.sort(np.real(np.linalg.eigvalsh(Heff)))
            print(f"6. |k| = {kmag:g}: twelve bond patterns, other edges relaxed, eigenvalues "
                  f"{np.round(w12, 5)};  family pair {np.round(np.real(np.linalg.eigvalsh(0.5*(Hff+Hff.conj().T))), 6)}")

    # 7. Longitudinal sector of the static register
    print("\n7. Longitudinal waves of the static register (units mu_bar = 1)")
    N2 = 1 / np.pi
    C11 = (3 - 4 * N2) / (1 - N2)       # D4 Born sums with the tangential contact
    lam, mu = C11 - 2.0, 1.0
    print(f"   C11/C44 = {C11:.4f}; second sound in the dynamical register at {np.sqrt(C11):.5f} c")
    roots = longitudinal_speeds(lam, mu, 0.0, 0.0)
    print(f"   u_4 free:  Q roots {np.round(roots, 6)}  (Q = -1 is the light cone)")
    for f_s in (1.0, 0.1):
        roots = longitudinal_speeds(lam, mu, f_s, 0.0)
        print(f"   u_4 = phase, reading (A), rho_s/rho = {f_s}: Q roots {np.round(roots, 4)}"
              f"  (complex: no propagating wave)")
    for p in (2, 4, 6):
        R = 10.0 ** (2 * p)                              # (v_p/c)^2
        roots = longitudinal_speeds(lam, mu, R ** 2, R)
        speeds = np.sort(np.sqrt(-roots.real))
        print(f"   u_4 = phase, reading (B), v_p/c = 1e{p}: speeds {speeds[0]:.5f} c and {speeds[1]:.4e} c")
    nu = lambda v: 4 / 7 * (11 / 4) ** (4 / 3) / v ** 3
    print(f"   Delta N_eff of one thermal boson: at 1.5915 c {nu(np.sqrt(C11)):.2f}; at c {nu(1.0):.2f}")


if __name__ == "__main__":
    main()
