#!/usr/bin/env python3
"""The edge mass, pushed to closure: what is derived, what remains, no fudging.

THE RULE THAT DISSOLVED THE FACTOR-100 (read from the monograph, not invented)
The framework's mass rule: the rest mass of a localised lattice particle is
the self-energy generated by the lattice's own potential acting on the defect
at zero momentum. The elastic strain-field energy (the Hirth-Lothe mu b^2 ell
~ m_0) renormalises the vacuum's elastic constants and is NOT particle mass.
This rule is not free to question here, because the electron already anchors
it: the electron's strain field also carries ~m_0 of elastic energy, yet its
mass is the PN amplitude alpha m_0 = m_e, correct to the ppb level. The same
rule applied to the edge says: the continuum linear-response integrals
(edge_born_huang.py, edge_core_absorption.py) computed chirality-induced
FIELD energy, which is vacuum renormalisation, not mass. Their ~0.01 was the
right answer to the wrong question. Retracted as a mass statement; retained
as the vacuum-renormalisation piece.

THE SOURCE THE VERTEX ACTUALLY SEES
"The lattice's own potential acting on the defect" means the misfit: the
disregistry across the glide plane, which is O(1) at the core, not the
elastic far-field harmonics, which carry 1/(3 pi)-type amplitudes. With the
PN slip phi(x) = (b/pi)(atan(x/w) + pi/2), the Frenkel misfit measure has an
exact closed form (sympy-verified):

    Int sin^2(pi phi/b) dx  =  pi w        (exactly)

so the misfit support per unit line is pi w, and the core layer weight is
pi w d_111. No cutoff enters: the PN width is the support.

THE GAP HAS A CLOSED FORM FROM CONTACT COUNTING
The intermediate is the core libration: the rotational excitation of nodes
adjacent to the glide plane at maximal misregistry. Of a node's 12 contacts,
3 cross the glide plane; at misregistry d/2 the Frenkel restoring of a
crossing contact is inverted. Local rotational restoring:
    2 kappa_c x (9 - 3)/12 = kappa_c,
so the libration gap is
    Delta = kappa_c ell^3 = [2N^2/(1-2N^2)] m_0 = 1.7519 m_0,
i.e. H = 2N^2/(1-2N^2), a closed form in the coupling number alone.

WHERE THE COEFFICIENT NOW STANDS
    m_1 = theta^2 m_0 x [ V^2 * (pi w d_111 / ell^2) / H ]
with V the per-node vertex factor on the misfit distortion, the one number
not yet derived. Everything else is closed-form:
    pi w d_111 = 1.162 (screw-precedent width w = 0.453)
               = 1.511 (edge Cosserat width L_b = 0.589, the brane value)
    H          = 1.752
Unity requires V = 1.23 (screw width) or V = 1.08 (brane width). We do NOT
adopt either; V is the open calculation, and it is a single per-node matrix
element on the discrete misfit, not a field-theory integral. The order-100
question is closed; the order-unity question is one number wide.

WHAT WOULD BE FUDGING, RECORDED SO IT CANNOT HAPPEN QUIETLY
- Choosing between w = 0.453 and L_b = 0.589 by which lands closer to 1.
- Absorbing V into "absorption" language without deriving it.
- Quoting the coefficient as confirmed. It is bracketed at [0.66, 0.86] x V^2
  with V ~ 1 expected and underived.
"""
import numpy as np, sympy as sp

def closed_forms():
    x,w,b = sp.symbols('x w b', positive=True)
    phi = (b/sp.pi)*(sp.atan(x/w)+sp.pi/2)
    I = sp.simplify(sp.integrate(sp.sin(sp.pi*phi/b)**2,(x,-sp.oo,sp.oo)))
    assert I == sp.pi*w
    return I

def main():
    N2=1/np.pi; H=2*N2/(1-2*N2); d111=np.sqrt(2/3)
    print("misfit support: Int sin^2(pi phi/b) dx =", closed_forms(), " (exact)")
    print(f"libration gap: H = 2N^2/(1-2N^2) = {H:.4f}   (contact counting)")
    for lab,w in [("screw-precedent width",0.453),("edge brane width L_b",0.589)]:
        geom=np.pi*w*d111
        print(f"  {lab:22s} w={w:.3f}: geometry {geom:.3f}, coeff = {geom/H:.3f} x V^2,"
              f"  V for unity = {np.sqrt(H/geom):.3f}")
    print("\nstatus: order closed, coefficient one underived number (V) wide.")

if __name__=="__main__":
    main()
